# Book settings
# More info at https://jupyterbook.org/customize/config.html

title: Reinforcement Learning
author: Helen Duncan
logo: tortoise.jpg

# Force re-execution of notebook on each build
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib
  
# Information on where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book # Online location of book
  path_to_book: docs # Optional - Path to the book relative to the repo root
  branch: main       # Optional - Branch of the repo that should be used when creating links

# Add GitHub buttons to your book
html:
  use_repository_button: true